"""
Generated by Microsoft Copilot
Improved by talentedbug

Be aware of potential copyright issues

This script renames all files in the current directory with a random hex name
"""

import os
import random

def generate_hex_name():
    return ''.join(random.choices('0123456789abcdef', k=20))

def rename_files_in_directory():
    for filename in os.listdir('.'):
        if os.path.isfile(filename) and filename.endswith('.mp4'):
            new_name = generate_hex_name() + '.mp4'
            os.rename(filename, new_name)

rename_files_in_directory()
